### ISSUE TITLE
Problema al ejectuar comando grunt

### ISSUE THREAD

**Issue by cmarrero01** [gonzaloruizdevilla/generator-angularexpress#1]
grunt
Running "jshint:all" (jshint) task
Linting Gruntfile.js ...ERROR
[L84:C9] W015: Expected '}' to have an indentation at 11 instead at 9.
        }
Linting Gruntfile.js ...ERROR
[L85:C7] W015: Expected ']' to have an indentation at 9 instead at 7.
      ],
Linting Gruntfile.js ...ERROR
[L86:C7] W015: Expected 'livereload' to have an indentation at 9 instead at 7.
      livereload: {
Linting Gruntfile.js ...ERROR
[L87:C9] W015: Expected 'options' to have an indentation at 11 instead at 9.
        options: {
Linting Gruntfile.js ...ERROR
[L88:C11] W015: Expected 'middleware' to have an indentation at 13 instead at 11
.
          middleware: function (connect) {
Linting Gruntfile.js ...ERROR
[L89:C13] W015: Expected 'return' to have an indentation at 15 instead at 13.
            return [
Linting Gruntfile.js ...ERROR
[L90:C15] W015: Expected 'lrSnippet' to have an indentation at 17 instead at 15.

```
          lrSnippet,
```

Linting Gruntfile.js ...ERROR
[L91:C15] W015: Expected 'proxySnippet' to have an indentation at 17 instead at
15.
              proxySnippet,
Linting Gruntfile.js ...ERROR
[L92:C15] W015: Expected 'mountFolder' to have an indentation at 17 instead at 1
5.
              mountFolder(connect, '.tmp'),
Linting Gruntfile.js ...ERROR
[L93:C15] W015: Expected 'mountFolder' to have an indentation at 17 instead at 1
5.
              mountFolder(connect, yeomanConfig.app)
Linting Gruntfile.js ...ERROR
[L94:C13] W015: Expected ']' to have an indentation at 15 instead at 13.
            ];
Linting Gruntfile.js ...ERROR
[L95:C11] W015: Expected '}' to have an indentation at 13 instead at 11.
          }
Linting Gruntfile.js ...ERROR
[L96:C9] W015: Expected '}' to have an indentation at 11 instead at 9.
        }
Linting Gruntfile.js ...ERROR
[L97:C7] W015: Expected '}' to have an indentation at 9 instead at 7.
      },
Linting Gruntfile.js ...ERROR
[L98:C7] W015: Expected 'test' to have an indentation at 9 instead at 7.
      test: {
Linting Gruntfile.js ...ERROR
[L99:C9] W015: Expected 'options' to have an indentation at 11 instead at 9.
        options: {
Linting Gruntfile.js ...ERROR
[L100:C11] W015: Expected 'middleware' to have an indentation at 13 instead at 1
1.
          middleware: function (connect) {
Linting Gruntfile.js ...ERROR
[L101:C13] W015: Expected 'return' to have an indentation at 15 instead at 13.
            return [
Linting Gruntfile.js ...ERROR
[L102:C15] W015: Expected 'mountFolder' to have an indentation at 17 instead at
15.
              mountFolder(connect, '.tmp'),
Linting Gruntfile.js ...ERROR
[L103:C15] W015: Expected 'mountFolder' to have an indentation at 17 instead at
15.
              mountFolder(connect, 'test')
Linting Gruntfile.js ...ERROR
[L104:C13] W015: Expected ']' to have an indentation at 15 instead at 13.
            ];
Linting Gruntfile.js ...ERROR
[L105:C11] W015: Expected '}' to have an indentation at 13 instead at 11.
          }
Linting Gruntfile.js ...ERROR
[L106:C9] W015: Expected '}' to have an indentation at 11 instead at 9.
        }
Linting Gruntfile.js ...ERROR
[L107:C7] W015: Expected '}' to have an indentation at 9 instead at 7.
      },
Linting Gruntfile.js ...ERROR
[L108:C7] W015: Expected 'dist' to have an indentation at 9 instead at 7.
      dist: {
Linting Gruntfile.js ...ERROR
[L109:C9] W015: Expected 'options' to have an indentation at 11 instead at 9.
        options: {
Linting Gruntfile.js ...ERROR
[L110:C11] W015: Expected 'middleware' to have an indentation at 13 instead at 1
1.
          middleware: function (connect) {
Linting Gruntfile.js ...ERROR
[L111:C13] W015: Expected 'return' to have an indentation at 15 instead at 13.
            return [
Linting Gruntfile.js ...ERROR
[L112:C15] W015: Expected 'mountFolder' to have an indentation at 17 instead at
15.
              mountFolder(connect, yeomanConfig.dist)
Linting Gruntfile.js ...ERROR
[L113:C13] W015: Expected ']' to have an indentation at 15 instead at 13.
            ];
Linting Gruntfile.js ...ERROR
[L114:C11] W015: Expected '}' to have an indentation at 13 instead at 11.
          }
Linting Gruntfile.js ...ERROR
[L115:C9] W015: Expected '}' to have an indentation at 11 instead at 9.
        }
Linting Gruntfile.js ...ERROR
[L116:C7] W015: Expected '}' to have an indentation at 9 instead at 7.
      }
Linting Gruntfile.js ...ERROR
[L117:C5] W015: Expected '}' to have an indentation at 7 instead at 5.
    },
Linting Gruntfile.js ...ERROR
[L118:C5] W015: Expected 'open' to have an indentation at 7 instead at 5.
    open: {
Linting Gruntfile.js ...ERROR
[L119:C7] W015: Expected 'server' to have an indentation at 9 instead at 7.
      server: {
Linting Gruntfile.js ...ERROR
[L120:C9] W015: Expected 'url' to have an indentation at 11 instead at 9.
        url: 'http://localhost:<%= connect.options.port %>'
Linting Gruntfile.js ...ERROR
[L121:C7] W015: Expected '}' to have an indentation at 9 instead at 7.
      }
Linting Gruntfile.js ...ERROR
[L122:C5] W015: Expected '}' to have an indentation at 7 instead at 5.
    },
Linting Gruntfile.js ...ERROR
[L123:C5] W015: Expected 'clean' to have an indentation at 7 instead at 5.
    clean: {
Linting Gruntfile.js ...ERROR
[L124:C7] W015: Expected 'dist' to have an indentation at 9 instead at 7.
      dist: {
Linting Gruntfile.js ...ERROR
[L125:C9] W015: Expected 'files' to have an indentation at 11 instead at 9.
        files: [{
Linting Gruntfile.js ...ERROR
[L126:C11] W015: Expected 'dot' to have an indentation at 13 instead at 11.
          dot: true,
Linting Gruntfile.js ...ERROR
[L127:C11] W015: Expected 'src' to have an indentation at 13 instead at 11.
          src: [
Linting Gruntfile.js ...ERROR
[L128:C13] W015: Expected '.tmp' to have an indentation at 15 instead at 13.
            '.tmp',
Linting Gruntfile.js ...ERROR
[L129:C13] W015: Expected '<%= yeoman.dist %>/_' to have an indentation at 15 in
stead at 13.
            '<%= yeoman.dist %>/_',
Linting Gruntfile.js ...ERROR
[L130:C13] W015: Expected '!<%= yeoman.dist %>/.git_' to have an indentation at
15 instead at 13.
            '!<%= yeoman.dist %>/.git_'
Linting Gruntfile.js ...ERROR
[L131:C11] W015: Expected ']' to have an indentation at 13 instead at 11.
          ]
Linting Gruntfile.js ...ERROR
[L132:C9] W015: Expected '}' to have an indentation at 11 instead at 9.
        }]
Linting Gruntfile.js ...ERROR
[L133:C7] W015: Expected '}' to have an indentation at 9 instead at 7.
      },
Linting Gruntfile.js ...ERROR

> > Too many errors. (32% scanned).

Warning: Task "jshint:all" failed. Use --force to continue.

Aborted due to warnings.

Elapsed time
jshint:all  143ms
Total       143ms

**Comment by cmarrero01** [comment]
Hola de nuevo, si bien no resolvi del todo el problema, al correr "grunt build" no sucede este error y hace todo correctamente. Tal vez ese dato ayude a resolver el problema

**Comment by gonzaloruizdevilla** [comment]
Es que el generador está pensado para usar tareas concretas de grunt, que están definidas en el gruntfile

Por otra parte, el express esta integrado con el connect que arranca grunt para poder tener un backend y poder testar en modo e2e peticiones xhr que no sean solo de tipo GET, sino también PUT, POST, etc. Por eso al hacer un build, en la carpeta dist no aparece nada de express. Digamos que no es un express para producción sino de ayuda al desarrollo del proyecto angular.

Se puede plantear incluir alguna tarea buildexpress o algo así para que empaquete el express también, pero no sería inmediato, habría que darle alguna vuelta para que tuviera sentido.

**Comment by cmarrero01** [comment]
Claro, Lo que para mi no tenia sentido es que si realizas todos los modelos de informacion con express para desarrollar la aplicacion, una vez que haces el build de la APP, todo lo que esta en express ya carece de sentido, ya que no podes ejecutar el archivo /server/main.js para abrir el servidor y que sirva de "server" de la aplicacion realizada y que trabaje con esos modelos, tal vez entendi mal el objetivo de incluir express dentro del generator, pense que la intension era crear modelos para ser consumidos desde el front end pero en ambiente de produccion. Seria muy bueno que acompañe al build el archivo que hace de servidor al proyecto, ya que de otro modo, se pierden todos los modelos realizados en express.. o me equivoco?

**Comment by gonzaloruizdevilla** [comment]
El planteamiento de este express es tener un servidor de mocks para la aplicación de AngularJS.  Este servidor está controlado por las personas que tienen skills de maquetación, JavaScript, etc. 

Como solemos funcionar nosotros es que en cada iteración, el equipo de front y de back se ponen de acuerdo en la interfaz de los servicios rest. Cuales son las urls que se invocarán, con qué parámetros de entrada, con qué salidas, etc.

El equipo de back desarrolla en paralelo al de front los servicios REST. Da igual la tecnología, pueden ser con node, con Java, con C# o la que toque. Desarrollan una API completa, con todas su pruebas unitarias y demás.

Por su parte, el equipo de front simula el servidor con su express, y puede jugar con los datos que envía al navegador para forzar presentaciones límites (con muchos datos o sin datos), pueden forzar errores de servidor para ver como actúa la presentación, pueden poner timers para ver como actúan las pantallas cuando tardan en llegar los datos, etc. Pero realmente en su proyecto express no conocen nada de los detalles de negocio y ni técnicos de la implementación de los servicios.

**Comment by cmarrero01** [comment]
Claro, entiendo... Yo suelo desarrollar APIs en CodeIgniter con PHP, por lo que estoy familiarizado con el concepto de servicios REST. Habia mal interpretado la intencion del express, aunque mas haya de mi error creo que la idea es muy buena para lograr tener mejor control de la informacion cuando se lanze a produccion.

Ahora en todo esto, solo me queda una gran duda.

Como se levanta el resultado en un server de node?, es decir, el resultado, la carpeta dist, contiene todo el proyecto pero ningun lounch para ejecutarlo desde node.js.

Muy bueno tu aporte y creo que de ahora en mas voy a encarar mis futuros proyectos con esta tecnologia, solo me falta terminar de comprender su logica de funcionamiento, que viniendo de OO es bastante complicada.

**Comment by gonzaloruizdevilla** [comment]
El resultado lo debes llevar a tu aplicación. Si la aplicación "real" es un node con express, deberías ponerlo en la carpeta de recursos públicos.

Aunque sigamos hablando del tema, marco la incidencia como resuelta.
